# Evaluation

defaults:
  - eval


mode: test # 'val' or 'test'


# eval settings
agent: cliport
n_demos: 100 # number of val instances
train_demos: 900 # training demos used to train model
n_repeats: 1 # number of repeats
gpu: [0]
save_results: True # write results to json
update_results: False # overwrite existing json results?
checkpoint_type: 'test_best'
val_on_heldout: True

disp: False
shared_memory: False
eval_task: stack-block-pyramid # task to evaluate the model on
model_task: stack-block-pyramid # task the model was trained on (e.g. multi-language-conditioned or packing-boxes-pairs-seen-colors)
type: my # 'single' or 'multi' or 'my'
batch_size: 3

# paths
model_dir: ${root_dir}
exp_folder: exps
data_dir: /home/constantin/thesis/GenSim_Reserved/data/GenSim_Data_Train/stack-block-pyramid/ # /home/cosmos/VScode Projects/coglab/GenSim/data/GenSim_Data_Train/data #/home/cosmos/VScode Projects/coglab/GenSim/data/ 
assets_root: ${root_dir}/environments/assets/

model_path: /home/constantin/thesis/GenSim_Reserved/data/GenSim_Data_Train/stack-block-pyramid/checkpoints # /home/cosmos/VScode Projects/coglab/GenSim/data/GenSim_Data_Train/checkpoints_without_depth/checkpoints/ #${model_dir}/${exp_folder}/${model_task}-${agent}-n${train_demos}-train/checkpoints/ # path to pre-trained models
train_config: /home/constantin/thesis/GenSim/cliport/cfg/train.yaml # /home/cosmos/VScode Projects/coglab/GenSim/cliport/cfg/train.yaml  #${model_dir}/${exp_folder}/${model_task}-${agent}-n${train_demos}-train/.hydra/config.yaml # path to train config
save_path: /home/constantin/thesis/GenSim_Reserved/data/GenSim_Data_Train/stack-block-pyramid/checkpoints #${model_dir}/${exp_folder}/${eval_task}-${agent}-n${train_demos}-train/checkpoints/ # path to save results
results_path: /home/constantin/thesis/GenSim_Reserved/data/GenSim_Data_Train/stack-block-pyramid/checkpoints  # /GenSim/data/GenSim_Data_Train/build-car/checkpoints/ # ${model_dir}/${exp_folder}/${eval_task}-${agent}-n${train_demos}-train/checkpoints/ # path to existing results


# record videos (super slow)
record:
  save_video: False
  save_video_path: ${model_dir}/videos/${exp_folder}/${eval_task}-${agent}-n${train_demos}-train/videos/
  add_text: False
  add_task_text: True
  fps: 20
  video_height: 640
  video_width: 720

dataset:
  type: 'single'
  images: True 
  cache: True 
  augment: 
    theta_sigma: 60
